import type { ReactNode } from "react";
import { Info, TriangleAlert } from "lucide-react";
import { cn } from "../../lib/utils";

/**
 * Something the manager needs told, in place, without being asked.
 *
 * Not a `sonner` toast and not a `Confirm`, and the three divide cleanly. A toast reports that something
 * you just did has happened, and it leaves. A confirm blocks until you answer. This is a CONDITION that
 * is true right now and stays on screen while it is: he is over budget, an injured man must come off, the
 * career would not open. Nothing to dismiss, because dismissing it would not make it untrue.
 *
 * It exists because the app had five of these written by hand in three different treatments — a bordered
 * box in one place, bare red text in another, gold text in a third — and TWO of them carried no `role` at
 * all, so a screen reader announced nothing when a contract offer was refused or the budget went over.
 * A warning nobody hears is not a warning.
 */

export type AlertTone = "danger" | "warn" | "info";

/*
 * The washes come through `bg-[var(--…)]` rather than an opacity modifier, and that is not a style
 * preference. These colours are `var()` references in the Tailwind config, so there are no channels for
 * `bg-gold/10` to compute an alpha from and it silently produces nothing — the same class of quiet failure
 * a stale config caused earlier. An arbitrary value reading the token is generated by source scanning, so
 * it cannot go missing.
 */
const TONE: Record<AlertTone, { box: string; text: string }> = {
  // A failure, or a thing that has gone wrong and needs answering.
  danger: { box: "border-danger bg-[var(--danger-soft)]", text: "text-danger" },
  // A standing condition worth noticing: over budget, a deal running down, a man to bring off.
  warn: { box: "border-gold bg-[var(--gold-soft)]", text: "text-gold" },
  // A fact, not a problem.
  info: { box: "border-border-strong bg-surface-2", text: "text-fg-muted" },
};

export function Alert({ tone = "warn", icon, children, className }: {
  tone?: AlertTone;
  /** Overrides the tone's own icon, for a condition with its own established mark. */
  icon?: ReactNode;
  children: ReactNode;
  className?: string;
}) {
  const { box, text } = TONE[tone];
  return (
    <div
      /*
       * `alert` is assertive and interrupts; `status` is polite and waits for a gap.
       *
       * Chosen by tone rather than left to the caller, because the distinction is about what the message
       * IS, not where it sits: a danger appeared in response to something and deserves the interruption,
       * while a warning that is simply true — over budget, a contract running down — would otherwise be
       * re-announced on every render of a screen the manager is reading calmly.
       */
      role={tone === "danger" ? "alert" : "status"}
      className={cn("flex items-start gap-2 rounded-md border px-3 py-2 text-sm", box, className)}
    >
      <span className={cn("mt-px shrink-0", text)}>
        {icon ?? (tone === "info" ? <Info className="size-4" /> : <TriangleAlert className="size-4" />)}
      </span>
      {/* The text is `fg`, not the tone colour: a whole sentence in red is harder to read than a sentence
          with a red mark beside it, and the border already carries the tone. */}
      <span className="min-w-0 flex-1 text-fg">{children}</span>
    </div>
  );
}
